android.useAndroidX=true
android.suppressUnsupportedCompileSdk=36
TruVideoReactTurboCameraSdk_kotlinVersion=2.2.0
TruVideoReactTurboCameraSdk_minSdkVersion=24
TruVideoReactTurboCameraSdk_targetSdkVersion=36
TruVideoReactTurboCameraSdk_compileSdkVersion=36
# Disable New Arch so we don't need React/codegen; AAR is plain Android library.
newArchEnabled=false
